name: Setup Rust Cache
description: Setup Rust dependency caching with restore and save

inputs:
  save-cache:
    description: Whether to save cache after build
    required: false
    default: 'false'

outputs:
  cache-hit:
    description: Whether cache was restored successfully
    value: ${{ steps.cache_restore.outputs.cache-hit }}

runs:
  using: composite
  steps:
    - name: Rust cache restore
      uses: actions/cache/restore@v4.2.0
      id: cache_restore
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          src-tauri/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Rust cache save
      if: inputs.save-cache == 'true'
      uses: actions/cache/save@v4.2.0
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          src-tauri/target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}