name: "Test Pake Action"

on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to package"
        required: true
        default: "https://weekly.tw93.fun"
      name:
        description: "App name"
        required: true
        default: "TestApp"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build Pake App
        id: build
        uses: ./
        with:
          url: ${{ github.event.inputs.url }}
          name: ${{ github.event.inputs.name }}
          debug: true

      - name: Upload Package
        uses: actions/upload-artifact@v4
        with:
          name: pake-app
          path: ${{ steps.build.outputs.package-path }}
